services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: movies_db
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - movies_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # NestJS API
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: movies_api
    restart: unless-stopped
    env_file:
      - ./.env
      - ./backend/.env
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - movies_network

  # # Frontend (Nginx placeholder - swap with your actual frontend image)
  frontend:
    build:
      context: ./movie-fe
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: movie-fe
    restart: unless-stopped
    depends_on:
      - api
    env_file:
      - ./movie-fe/.env.local
    ports:
      - "3000:3000"

volumes:
  postgres_data:

networks:
  movies_network:
    driver: bridge